language: node_js
node_js:
  - "node"
cache:
  - npm
  - cargo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: false
  fqdn: $FQDN
  local_dir: dist/
  on:
    branch: source
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="${HOME}/.cargo/bin:$PATH"
script:
  - npm run test
  - npm run lint
  - npm run build:prod
