language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn
install:
  - yarn install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: false
  fqdn: $FQDN
  local_dir: dist/
  on:
    branch: source
script:
  - yarn run test
  - yarn run lint
  - yarn run build:prod
